INSERT INTO genres (name) VALUES
                              ('Action'),
                              ('Adventure'),
                              ('Biography'),
                              ('Business'),
                              ('Children'),
                              ('Classic'),
                              ('Comedy'),
                              ('Crime'),
                              ('Drama'),
                              ('Dystopian'),
                              ('Fantasy'),
                              ('Historical Fiction'),
                              ('History'),
                              ('Horror'),
                              ('Manga'),
                              ('Mystery'),
                              ('Philosophy'),
                              ('Poetry'),
                              ('Psychology'),
                              ('Romance'),
                              ('Science'),
                              ('Science Fiction'),
                              ('Self-Help'),
                              ('Technology'),
                              ('Thriller');